language: java
sudo: required
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
jdk:
- openjdk8
script: mvn package -ff -B
before_install:
- chmod -R 777 ./travis/init-travis-build.sh
- "./travis/init-travis-build.sh"
install:
- mvn -T 10 install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dcheckstyle.skip=true
  -Dfindbugs.skip=true
after_success:
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- "./travis/deploy-to-sonatype.sh"
env:
  global:
  - secure: h7i6jU8n9jS4iEzgCkZ/1iM7LsNvnyHspRq/Zmf9lT9rWRG47YZvmuPPgb4QITCLHD3pDDpZbQIIZNud/n7XQqNbgkAsp8w0Oolsg4feiLqRH61Jr8MTcf5HnKxRH3pdACG0qkCi35sJ5FozIhNwZllJNie0kgjhDYDJPfNIkRk=
  - secure: iMvUq8MPhU1Xyjtg5OP8RJHYSmwLZIu/LiUC5NCCc1/UoOuJEJrihHwsQTf//OzjWVwRMl4HeDxuLhx9GQVZpaoz9JYJY496Hi0HketZYWTQgx+b9wfI3gGDXVi5MebvQ4p3rKKnR8pmeTmKqFTALamkEJadh4YBKfGckN/93RI=
